/*
 * MU0918 AndroidAuto2ListenerDistributor, rebuilt for the SQ5 Android Auto -> luka adapter.
 * Generated by aa-luka/java/gen_distributor.py - do not edit by hand.
 */
package de.audi.app.terminalmode.smartphone.androidauto2;

import de.audi.app.terminalmode.IContext;
import de.audi.atip.log.LogChannel;
import java.util.Vector;
import org.dsi.ifc.androidauto2.CallState;
import org.dsi.ifc.androidauto2.DSIAndroidAuto2Listener;
import org.dsi.ifc.androidauto2.PlaybackInfo;
import org.dsi.ifc.androidauto2.TelephonyState;
import org.dsi.ifc.androidauto2.TrackData;
import org.dsi.ifc.global.ResourceLocator;

public class AndroidAuto2ListenerDistributor
implements DSIAndroidAuto2Listener {
    private static final String LOGCLASS = "AndroidAuto2ListenerDistributor";
    private final LogChannel logger;
    private final Vector listeners = new Vector();

    public AndroidAuto2ListenerDistributor(IContext iContext) {
        this.logger = iContext.getLogger().dsi();
        try {
            com.sq5.aa.luka.AaLukaBridge.attach(this, iContext);
        }
        catch (Throwable t) {
            /* the bridge must never stop Android Auto from starting */
        }
    }

    public void addListener(DSIAndroidAuto2Listener[] dSIAndroidAuto2ListenerArray) {
        synchronized (this.listeners) {
            for (int i = 0; i < dSIAndroidAuto2ListenerArray.length; ++i) {
                this.listeners.addElement(dSIAndroidAuto2ListenerArray[i]);
            }
        }
    }

    /** Added for the SQ5 Android Auto adapter: same effect as addListener for one listener. */
    public void addSingleListener(DSIAndroidAuto2Listener listener) {
        synchronized (this.listeners) {
            this.listeners.addElement(listener);
        }
    }

    private DSIAndroidAuto2Listener[] snapshot() {
        synchronized (this.listeners) {
            DSIAndroidAuto2Listener[] ls = new DSIAndroidAuto2Listener[this.listeners.size()];
            this.listeners.copyInto(ls);
            return ls;
        }
    }
    public void asyncException(int n, String string, int n2) {
        if (this.logger.isDebug2()) {
            this.logger.log(100000000, "[%1.asyncException]", (Object)"AndroidAuto2ListenerDistributor");
        }
        DSIAndroidAuto2Listener[] ls = this.snapshot();
        for (int i = 0; i < ls.length; ++i) {
            ls[i].asyncException(n, string, n2);
        }
    }
    public void videoFocusRequestNotification(int n, int n2) {
        if (this.logger.isDebug2()) {
            this.logger.log(100000000, "[%1.videoFocusRequestNotification]", (Object)"AndroidAuto2ListenerDistributor");
        }
        DSIAndroidAuto2Listener[] ls = this.snapshot();
        for (int i = 0; i < ls.length; ++i) {
            ls[i].videoFocusRequestNotification(n, n2);
        }
    }
    public void videoAvailable(boolean bl, int n) {
        if (this.logger.isDebug2()) {
            this.logger.log(100000000, "[%1.videoAvailable]", (Object)"AndroidAuto2ListenerDistributor");
        }
        DSIAndroidAuto2Listener[] ls = this.snapshot();
        for (int i = 0; i < ls.length; ++i) {
            ls[i].videoAvailable(bl, n);
        }
    }
    public void audioFocusRequestNotification(int n, int n2) {
        if (this.logger.isDebug2()) {
            this.logger.log(100000000, "[%1.audioFocusRequestNotification]", (Object)"AndroidAuto2ListenerDistributor");
        }
        DSIAndroidAuto2Listener[] ls = this.snapshot();
        for (int i = 0; i < ls.length; ++i) {
            ls[i].audioFocusRequestNotification(n, n2);
        }
    }
    public void audioAvailable(int n, boolean bl, int n2) {
        if (this.logger.isDebug2()) {
            this.logger.log(100000000, "[%1.audioAvailable]", (Object)"AndroidAuto2ListenerDistributor");
        }
        DSIAndroidAuto2Listener[] ls = this.snapshot();
        for (int i = 0; i < ls.length; ++i) {
            ls[i].audioAvailable(n, bl, n2);
        }
    }
    public void voiceSessionNotification(int n, int n2) {
        if (this.logger.isDebug2()) {
            this.logger.log(100000000, "[%1.voiceSessionNotification]", (Object)"AndroidAuto2ListenerDistributor");
        }
        DSIAndroidAuto2Listener[] ls = this.snapshot();
        for (int i = 0; i < ls.length; ++i) {
            ls[i].voiceSessionNotification(n, n2);
        }
    }
    public void microphoneRequestNotification(int n, int n2) {
        if (this.logger.isDebug2()) {
            this.logger.log(100000000, "[%1.microphoneRequestNotification]", (Object)"AndroidAuto2ListenerDistributor");
        }
        DSIAndroidAuto2Listener[] ls = this.snapshot();
        for (int i = 0; i < ls.length; ++i) {
            ls[i].microphoneRequestNotification(n, n2);
        }
    }
    public void navFocusRequestNotification(int n, int n2) {
        if (this.logger.isDebug2()) {
            this.logger.log(100000000, "[%1.navFocusRequestNotification]", (Object)"AndroidAuto2ListenerDistributor");
        }
        DSIAndroidAuto2Listener[] ls = this.snapshot();
        for (int i = 0; i < ls.length; ++i) {
            ls[i].navFocusRequestNotification(n, n2);
        }
    }
    public void updateCallState(CallState[] callStateArray, int n) {
        if (this.logger.isDebug2()) {
            this.logger.log(100000000, "[%1.updateCallState]", (Object)"AndroidAuto2ListenerDistributor");
        }
        DSIAndroidAuto2Listener[] ls = this.snapshot();
        for (int i = 0; i < ls.length; ++i) {
            ls[i].updateCallState(callStateArray, n);
        }
    }
    public void updateTelephonyState(TelephonyState telephonyState, int n) {
        if (this.logger.isDebug2()) {
            this.logger.log(100000000, "[%1.updateTelephonyState]", (Object)"AndroidAuto2ListenerDistributor");
        }
        DSIAndroidAuto2Listener[] ls = this.snapshot();
        for (int i = 0; i < ls.length; ++i) {
            ls[i].updateTelephonyState(telephonyState, n);
        }
    }
    public void updateNowPlayingData(TrackData trackData, int n) {
        if (this.logger.isDebug2()) {
            this.logger.log(100000000, "[%1.updateNowPlayingData]", (Object)"AndroidAuto2ListenerDistributor");
        }
        DSIAndroidAuto2Listener[] ls = this.snapshot();
        for (int i = 0; i < ls.length; ++i) {
            ls[i].updateNowPlayingData(trackData, n);
        }
    }
    public void updatePlaybackState(PlaybackInfo playbackInfo, int n) {
        if (this.logger.isDebug2()) {
            this.logger.log(100000000, "[%1.updatePlaybackState]", (Object)"AndroidAuto2ListenerDistributor");
        }
        DSIAndroidAuto2Listener[] ls = this.snapshot();
        for (int i = 0; i < ls.length; ++i) {
            ls[i].updatePlaybackState(playbackInfo, n);
        }
    }
    public void updatePlayposition(int n, int n2) {
        DSIAndroidAuto2Listener[] ls = this.snapshot();
        for (int i = 0; i < ls.length; ++i) {
            ls[i].updatePlayposition(n, n2);
        }
    }
    public void updateCoverArtUrl(ResourceLocator resourceLocator, int n) {
        if (this.logger.isDebug2()) {
            this.logger.log(100000000, "[%1.updateCoverArtUrl]", (Object)"AndroidAuto2ListenerDistributor");
        }
        DSIAndroidAuto2Listener[] ls = this.snapshot();
        for (int i = 0; i < ls.length; ++i) {
            ls[i].updateCoverArtUrl(resourceLocator, n);
        }
    }
    public void updateNavigationNextTurnEvent(String string, int n, int n2, int n3, int n4, int n5) {
        if (this.logger.isDebug2()) {
            this.logger.log(100000000, "[%1.updateNavigationNextTurnEvent]", (Object)"AndroidAuto2ListenerDistributor");
        }
        DSIAndroidAuto2Listener[] ls = this.snapshot();
        for (int i = 0; i < ls.length; ++i) {
            ls[i].updateNavigationNextTurnEvent(string, n, n2, n3, n4, n5);
        }
    }
    public void updateNavigationNextTurnDistance(int n, int n2, int n3) {
        if (this.logger.isDebug2()) {
            this.logger.log(100000000, "[%1.updateNavigationNextTurnDistance]", (Object)"AndroidAuto2ListenerDistributor");
        }
        DSIAndroidAuto2Listener[] ls = this.snapshot();
        for (int i = 0; i < ls.length; ++i) {
            ls[i].updateNavigationNextTurnDistance(n, n2, n3);
        }
    }
    public void setExternalDestination(double d2, double d3, String string, String string2, int n) {
        if (this.logger.isDebug2()) {
            this.logger.log(100000000, "[%1.setExternalDestination]", (Object)"AndroidAuto2ListenerDistributor");
        }
        DSIAndroidAuto2Listener[] ls = this.snapshot();
        for (int i = 0; i < ls.length; ++i) {
            ls[i].setExternalDestination(d2, d3, string, string2, n);
        }
    }
    public void bluetoothPairingRequest(String string, int n) {
        if (this.logger.isDebug2()) {
            this.logger.log(100000000, "[%1.bluetoothPairingRequest]", (Object)"AndroidAuto2ListenerDistributor");
        }
        DSIAndroidAuto2Listener[] ls = this.snapshot();
        for (int i = 0; i < ls.length; ++i) {
            ls[i].bluetoothPairingRequest(string, n);
        }
    }
}
