"""Generate our AndroidAuto2ListenerDistributor from the MU0918 decompile.

Same class, same public API, same fan-out order. Two changes only:
  * Audi's generics list (GList/Generics, which jxe2jar cannot convert) -> java.util.Vector snapshot
  * the constructor also registers com.sq5.aa.luka.AaLukaBridge (guarded, never throws)
Plus a conversion fix: jxe2jar byte-swapped every ldc int in lsd.jar, so the decompile's
LogChannel levels read 14808325 instead of 100000000; every ldc-range int literal is un-swapped.
Also strips Java 5+ syntax (@Override) for -source 1.4.
"""
import os
import pathlib
import re
import struct
import sys

HERE = pathlib.Path(__file__).resolve().parent
STOCK_SOURCE = pathlib.Path(os.environ.get('FIRMWARE_SOURCE_DIR', str(HERE / 'firmware-source')))
SRC = STOCK_SOURCE / 'de/audi/app/terminalmode/smartphone/androidauto2/AndroidAuto2ListenerDistributor.java'
DST = HERE / 'build/gen/de/audi/app/terminalmode/smartphone/androidauto2/AndroidAuto2ListenerDistributor.java'

text = SRC.read_text(encoding='utf8')

# jxe2jar byte-swapped every ldc int/float in lsd.jar (100000000 -> 14808325); CFR copied them.
# Literals outside the bipush/sipush range were ldc constants: swap each back.  build.sh's
# fidelity gate checks the result against the stock class.
def unswap(m):
    v = int(m.group(2))
    if -32768 <= v <= 32767 or not -2**31 <= v < 2**31:
        return m.group(0)
    return m.group(1) + str(struct.unpack('<i', struct.pack('>i', v))[0])
text, n_swapped = re.subn(r'([^\w.])(-?\d+)(?![\w.])', unswap, text)
if n_swapped != 17 or '14808325' in text:
    sys.exit('expected 17 swapped log levels (14808325), un-swapped %d' % n_swapped)

# Fan-out loops -> snapshot array loops
loop = re.compile(
    r'GIterator gIterator = this\.listeners\.iterator\(\);\n'
    r'(\s*)while \(gIterator\.hasNext\(\)\) \{\n'
    r'\s*\(\(DSIAndroidAuto2Listener\)gIterator\.next\(\)\)\.(\w+)\((.*)\);\n'
    r'\s*\}')
text, n_loops = loop.subn(
    lambda m: ('DSIAndroidAuto2Listener[] ls = this.snapshot();\n'
               f'{m.group(1)}for (int i = 0; i < ls.length; ++i) {{\n'
               f'{m.group(1)}    ls[i].{m.group(2)}({m.group(3)});\n'
               f'{m.group(1)}}}'),
    text)

replacements = [
    ('import de.audi.atip.utils.generics.GCollection;\n', ''),
    ('import de.audi.atip.utils.generics.GIterator;\n', ''),
    ('import de.audi.atip.utils.generics.GList;\n', ''),
    ('import de.audi.atip.utils.generics.Generics;\n', ''),
    ('import de.audi.atip.log.LogChannel;\n', 'import de.audi.atip.log.LogChannel;\nimport java.util.Vector;\n'),
    ('    private static final String LOGCLASS;\n',
     '    private static final String LOGCLASS = "AndroidAuto2ListenerDistributor";\n'),
    ('    private final GList listeners = Generics.newCopyOnWriteArrayList();\n',
     '    private final Vector listeners = new Vector();\n'),
    ('        this.logger = iContext.getLogger().dsi();\n    }\n',
     '        this.logger = iContext.getLogger().dsi();\n'
     '        try {\n'
     '            com.sq5.aa.luka.AaLukaBridge.attach(this, iContext);\n'
     '        }\n'
     '        catch (Throwable t) {\n'
     '            /* the bridge must never stop Android Auto from starting */\n'
     '        }\n'
     '    }\n'),
    ('        this.listeners.addAll((GCollection)Generics.newArrayList((Object[])dSIAndroidAuto2ListenerArray));\n',
     '        synchronized (this.listeners) {\n'
     '            for (int i = 0; i < dSIAndroidAuto2ListenerArray.length; ++i) {\n'
     '                this.listeners.addElement(dSIAndroidAuto2ListenerArray[i]);\n'
     '            }\n'
     '        }\n'
     '    }\n\n'
     '    /** Added for the SQ5 Android Auto adapter: same effect as addListener for one listener. */\n'
     '    public void addSingleListener(DSIAndroidAuto2Listener listener) {\n'
     '        synchronized (this.listeners) {\n'
     '            this.listeners.addElement(listener);\n'
     '        }\n'
     '    }\n\n'
     '    private DSIAndroidAuto2Listener[] snapshot() {\n'
     '        synchronized (this.listeners) {\n'
     '            DSIAndroidAuto2Listener[] ls = new DSIAndroidAuto2Listener[this.listeners.size()];\n'
     '            this.listeners.copyInto(ls);\n'
     '            return ls;\n'
     '        }\n'),
]
for old, new in replacements:
    if old not in text:
        sys.exit('pattern not found: %r' % old)
    text = text.replace(old, new)

text = re.sub(r'\n\s*@Override', '', text)
text = re.sub(r'/\*\n \* Decompiled with CFR.*?\*/\n', '/*\n * MU0918 AndroidAuto2ListenerDistributor, rebuilt for the SQ5 Android Auto -> luka adapter.\n * Generated by aa-luka/java/gen_distributor.py - do not edit by hand.\n */\n', text, flags=re.S)

left = [w for w in ('GIterator', 'GList', 'Generics', 'GCollection', '@Override') if w in text]
if left:
    sys.exit('leftover tokens: %s' % left)

DST.parent.mkdir(parents=True, exist_ok=True)
DST.write_text(text, encoding='utf8', newline='\n')
print('wrote %s (%d fan-out loops rewritten, %d ldc ints un-swapped)' % (DST.relative_to(HERE), n_loops, n_swapped))
