"""Generate our AndroidAuto2NavHandler from the MU0918 decompile.

Same class, same behavior. One addition: the constructor subscribes the Android Auto DSI to the
next-turn attributes, which stock Audi never requests (AndroidAuto2EventListener only asks for
now-playing/play-position {3, 5}). Without this subscription gal does not forward Google Maps
turn-by-turn to the HMI at all. NotificationProxy.setNotification is additive (addIfAbsent) and
replays the full list when the DSI reconnects, so Audi's own subscriptions stay intact.
"""
import os
import pathlib
import re
import sys

HERE = pathlib.Path(__file__).resolve().parent
REL = 'de/audi/app/terminalmode/smartphone/androidauto2/nav/AndroidAuto2NavHandler.java'
STOCK_SOURCE = pathlib.Path(os.environ.get('FIRMWARE_SOURCE_DIR', str(HERE / 'firmware-source')))
SRC = STOCK_SOURCE / REL
DST = HERE / 'build/gen' / REL

text = SRC.read_text(encoding='utf8')

replacements = [
    ('    private static final String LOGCLASS;\n',
     '    private static final String LOGCLASS = "AndroidAuto2NavHandler";\n'),
    ('        super(logChannel, dSIAndroidAuto2, iStateHandler, iContext);\n    }\n',
     '        super(logChannel, dSIAndroidAuto2, iStateHandler, iContext);\n'
     '        try {\n'
     '            com.sq5.aa.luka.AaLukaBridge.subscribeNavigation(dSIAndroidAuto2);\n'
     '        }\n'
     '        catch (Throwable t) {\n'
     '            /* the bridge must never stop Android Auto from starting */\n'
     '        }\n'
     '    }\n'),
]
for old, new in replacements:
    if old not in text:
        sys.exit('pattern not found: %r' % old)
    text = text.replace(old, new)

text = re.sub(r'\n\s*@Override', '', text)
text = re.sub(r'/\*\n \* Decompiled with CFR.*?\*/\n',
              '/*\n * MU0918 AndroidAuto2NavHandler, rebuilt for the SQ5 Android Auto -> luka adapter.\n'
              ' * Generated by aa-luka/java/gen_navhandler.py - do not edit by hand.\n */\n',
              text, flags=re.S)
if '@Override' in text:
    sys.exit('leftover @Override')
# the lsd.jxe -> jar conversion byte-swapped large int constants: log level 1000000 reads 1078071040
text = text.replace('1078071040', '1000000')

DST.parent.mkdir(parents=True, exist_ok=True)
DST.write_text(text, encoding='utf8', newline='\n')
print('wrote %s' % DST.relative_to(HERE))
