"""Generate our AppConnectorTerminalMode from the MU0918 decompile (re/src, CFR).

Same class, same members, same behaviour outside an Android Auto session. Changes:
  * the constructor builds com.sq5.aa.coverart.AaCoverArtConnector (guarded, never throws)
  * added override updateCurrentStation: connector.beforeStation(info), then the stock update
    (luka's pushCoverArt-before-super order, as stock AppConnectorMedia does)
  * added override notifyAudioApplicationInFocusChanged: stock, then connector.focusChanged
  * jxe2jar byte-swapped the int log levels in the ldc pool (0x000F4240 -> 0x40420F00):
    restored to 1000000 / 10000000 (luka's MU-decompile values)
  * @Override stripped for -source 1.4
Usage: python gen_connector.py <out_dir>   (writes <out_dir>/de/audi/app/combi/bap/app/audio/...)
"""
import os
import pathlib
import re
import sys

HERE = pathlib.Path(__file__).resolve().parent
STOCK_SOURCE = pathlib.Path(os.environ.get('FIRMWARE_SOURCE_DIR', str(HERE / 'firmware-source')))
SRC = STOCK_SOURCE / 'de/audi/app/combi/bap/app/audio/AppConnectorTerminalMode.java'
OUT = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else HERE / 'build/gen')
DST = OUT / 'de/audi/app/combi/bap/app/audio/AppConnectorTerminalMode.java'

text = SRC.read_text(encoding='utf8')

replacements = [
    ('import de.audi.atip.interapp.combi.bap.audio.data.CombiBAPAudioSource;\n',
     'import de.audi.atip.interapp.combi.bap.audio.data.CombiBAPAudioSource;\n'
     'import de.audi.atip.interapp.combi.bap.audio.data.CombiBAPCurrentStationInfo;\n'),
    ('import de.vw.mib.bap.generated.audiosd.serializer.PlayPosition_Status;\n',
     'import de.vw.mib.bap.generated.audiosd.serializer.PlayPosition_Status;\n'
     'import com.sq5.aa.coverart.AaCoverArtConnector;\n'),
    ('implements CombiBAPServiceTerminalMode {\n'
     '    protected AppConnectorTerminalMode(CombiModuleAudio combiModuleAudio) {\n'
     '        super(combiModuleAudio);\n'
     '    }\n',
     'implements CombiBAPServiceTerminalMode {\n'
     '    /* SQ5: Android Auto cover art on the VC (no-op outside an Android Auto session) */\n'
     '    private AaCoverArtConnector aaCoverArt;\n'
     '\n'
     '    protected AppConnectorTerminalMode(CombiModuleAudio combiModuleAudio) {\n'
     '        super(combiModuleAudio);\n'
     '        try {\n'
     '            this.aaCoverArt = AaCoverArtConnector.create(combiModuleAudio.getPictureManager(),\n'
     '                new AaCoverArtConnector.Owner() {\n'
     '                    public boolean inFocus() {\n'
     '                        return AppConnectorTerminalMode.this.isAudioApplicationInFocus();\n'
     '                    }\n'
     '\n'
     '                    public void resend(CombiBAPCurrentStationInfo info) {\n'
     '                        AppConnectorTerminalMode.this.updateCurrentStation(info);\n'
     '                    }\n'
     '                });\n'
     '        }\n'
     '        catch (Throwable t) {\n'
     '            /* cover art must never stop the combi audio module from starting */\n'
     '        }\n'
     '    }\n'
     '\n'
     '    public void updateCurrentStation(CombiBAPCurrentStationInfo combiBAPCurrentStationInfo) {\n'
     '        if (this.aaCoverArt != null) {\n'
     '            this.aaCoverArt.beforeStation(combiBAPCurrentStationInfo);\n'
     '        }\n'
     '        super.updateCurrentStation(combiBAPCurrentStationInfo);\n'
     '    }\n'
     '\n'
     '    public void notifyAudioApplicationInFocusChanged(int n) {\n'
     '        super.notifyAudioApplicationInFocusChanged(n);\n'
     '        if (this.aaCoverArt != null) {\n'
     '            this.aaCoverArt.focusChanged(this.isAudioApplicationInFocus());\n'
     '        }\n'
     '    }\n'),
]
for old, new in replacements:
    if text.count(old) != 1:
        sys.exit('pattern not found exactly once: %r' % old[:80])
    text = text.replace(old, new)

# jxe2jar byte-swapped int constants (checked against javap -c of lsd.jar by build.sh)
for bad, good in (('1078071040', '1000000'), ('-2137614336', '10000000')):
    if bad not in text:
        sys.exit('expected swapped log level %s not found' % bad)
    text = text.replace('log(' + bad + ',', 'log(' + good + ',')
if re.search(r'log\((1078071040|-2137614336),', text):
    sys.exit('swapped log level left')

text = re.sub(r'\n\s*@Override', '', text)
text = re.sub(r'/\*\n \* Decompiled with CFR.*?\*/\n',
              '/*\n * MU0918 AppConnectorTerminalMode, rebuilt for the SQ5 Android Auto cover art.\n'
              ' * Generated by aa-luka/coverart/gen_connector.py - do not edit by hand.\n */\n', text, flags=re.S)
if '@Override' in text:
    sys.exit('leftover @Override')

DST.parent.mkdir(parents=True, exist_ok=True)
DST.write_text(text, encoding='utf8', newline='\n')
print('wrote %s' % DST)
